### ISSUE TITLE
Some questions rather than an issue

### ISSUE THREAD

**Issue by FMalcolm** [VSoftTechnologies/Delphi-Mocks#104] opened 2016-08-21 13:58 UTC
Using XE2, trying to compile latest Delphi-Mocks. In Delphi.Mocks...
1) (many) TTypeInfo does not contain a member names 'NameStr'. (Should it be 'Name'?)
2) (Line 182) class function Create(const ACreateObjectFunc: TFunc<T> = nil): TStub<T>; static;
    E2086 Type 'TFunc<TResult>' is not yet completely defined
3) Second _implementation_ of ItRec.IsIn<T> & ItRec.IsNotIn<T> complains that identifier is redeclared
4) (Lines 941, 942) 'TValue' does not contain a member named 'RttiType'

What am I missing?

**Comment by vincentparrett** [comment] 2016-08-21 23:11
Looks like we somehow included changes from later versions that are not backwards compatible. Will look into it.

**Comment by FMalcolm** [comment] 2016-08-21 23:12
Thanks Vincent

**Comment by vincentparrett** [comment] 2016-08-22 00:11
Ok, I have pushed a fix, turned out to be caused by 2 things, one, a pull request that included a DUnitX unit (that also didn't work on XE2), and a compiler bug in XE2 which I managed to work around by re-ordering parameters and adding an overload.

**Closed by vincentparrett** 2016-08-22 00:11 UTC
