### ISSUE TITLE
XE7 issue with mocked private methods

### ISSUE THREAD

**Issue by GallaherMike** [VSoftTechnologies/Delphi-Mocks#60] opened 2015-02-19 17:54 UTC
We are moving from XE5 to XE7. We have several tests that worked fine in XE5 but are breaking in XE7. Specifically using WillExecute no longer seems to work for Protected and Private methods.

We have code similar to the following...

FMockDO  : TMock<TDataObject>; 

FMockDO.Setup.WillExecute( 'GetDataset',
          function (const args : TArray<TValue>; const ReturnType : TRttiType) : TValue
          begin
            case RefCnt of
              1: Result := FCDS1;
              2: Result := FCDS2;
            end;
          end
         );

TDataObject is declared as the following

  {$RTTI EXPLICIT METHODS([vcPublic, vcPublished, vcProtected, vcPrivate]) PROPERTIES([vcPublic, vcPublished])}
  TDataObject = class( TComponent )
  private
  ...
  protected
   ...
    function  GetDataset: TDataset;virtual;
   ...
  public
  ...

If I move the GetDataset method to the public section the test runs just fine. 

For now we have created a hack class that promotes the visibility of that method for testing, but wanted to report the regression.

Thanks
MGallaher

**Comment by staticcat** [comment] 2015-11-15 23:06
Just some summary notes for myself when I return to this;
- Between XE5 to XE7 protected and private methods WillExecute no longer works. 
- This is an object mocking issue. 
- The called method is protected on a TComponent descendant.

**Comment by staticcat** [comment] 2015-11-15 23:19
Thanks for reporting this. Thinking about this now I would have expected it to break when we changed the virtual interface class and its method of execution. I will have to write some tests around this to verify my thoughts. 

Another issue that this raises is the scope of Delphi-Mocks. Honestly I must say the limits I had placed on mocking were the following;
- Allow mocking of all interfaced methods. 
- Allow mocking of virtual public class methods.

The main reason for this was two fold;
1. To limit the work required by the mocking library. 
2. Unit testing is typically (and I know people have historical applications built other ways) is about testing a single unit of code. Mocking helps "fake" external functionality of other objects used in single unit of code. 

I can understand the desire to mock a data object, however is testing that the dataobjects internals are triggered by the single unit of code going a step too far?

Also please let me know if my thinking around the use case here is not correct. From my understanding the mock is being used something like this;

found := sutDataConsumer.FindXItem(FMockDO, X);
Assert.IsTrue(found, "FindXItem should have found X in dataset FCDS1");

Currently my belief is that this should be a use case as certain controls, and 3rd party tools don't expose the ability to mock their public interface. Therefore extending my "Allow mocking of virtual public class methods" to be "Allow mocking of any virtual methods".

Anyone else have any other thoughts?

**Comment by sglienke** [comment] 2016-05-25 14:14
@GallaherMike Since you mention that you upgraded von XE5 to XE7 - could it be that the $RTTI directive is not in the same unit as your class and that it worked in XE5 because of this bug? http://qc.embarcadero.com/wc/qcmain.aspx?d=79943

I cannot reproduce the behavior you are describing when putting the $RTTI directive right above my TDataObject class because the RTTI contains it.

**Comment by vincentparrett** [comment] 2020-04-10 04:38
Closing this since mocking private and protected methods is really not a good idea, since (without hackery) code using those instances is really only calling it's public interface.

**Closed by vincentparrett** 2020-04-10 04:38 UTC
