### ISSUE TITLE
IExpect<T> has GUID... it must not!

### ISSUE THREAD

**Issue by LK-Daniel** [VSoftTechnologies/Delphi-Mocks#89] opened 2016-04-06 13:45 UTC
https://github.com/VSoftTechnologies/Delphi-Mocks/blob/master/Delphi.Mocks.pas#L46

Note that Generic Interfaces in Delphi must *not* contain a GUID, otherwise incompatible specializations of the same Generic Interface type will be castable without any warning.

**Comment by vincentparrett** [comment] 2016-04-06 23:06
In most cases I would agree with you, but in this case none of those interfaces is designed to be castable outside of delphi mocks. If you remove the guids, delphi-mocks will not compile.

Are you actually seeing a problem caused by this?

**Comment by sglienke** [comment] 2016-05-02 13:32
@LK-Daniel That statement is not completely true. If you are operating inside a generic class hierarchy having GUIDs on generic interfaces it completely valid and if these interfaces are for framework only purpose there is no problem at all.

The problem only arises when you call supports on an interface or object and ask for IExpect<X> whereas it has IExpect<Y> implemented but succeeds because all have the same GUID.

**Comment by staticcat** [comment] 2016-06-01 01:35
Closing as "IExpect<T>" is not designed to be inherited from. When we have a use case for it we can pick this issue up again.

**Closed by staticcat** 2016-06-01 01:35 UTC
